- name: Pool repository4
  hosts: staging
  become: true
  tasks:

  - name: stop all docker containers
    shell: docker stop $(docker ps -a -q)
    ignore_errors: true

  - name: remove all docker containers
    shell: docker rm $(docker ps -a -q)
    ignore_errors: true

  - name: Remove image
    docker_image:
      name: harter/repository4
      state: absent

  - name: Pull image
    docker_image:
      name: harter/repository4

  - name: Start harter/repository4
    shell: docker run -d -p 80:5000 harter/repository4
 
